version: '3'
services:
  fastapi-app:
    image: my-fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads  # Map the uploads directory
    depends_on:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:6.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    volumes:
      - ./kafka-data:/var/lib/kafka/data  # Map Kafka data directory
